[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"  # 최신 안정 버전 사용
optimizer = true
optimizer_runs = 200
via_ir = false

# Kaia 블록체인 RPC 설정
[rpc_endpoints]
kaia-mainnet = "https://public-en-cypress.klaytn.net"
kaia-testnet = "https://public-en-baobab.klaytn.net"

# 테스트 설정
[profile.default.fuzz]
runs = 256

# 가스 최적화 설정
[profile.ci]
optimizer = true
optimizer_runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
